# Postgres container for the Purple Robot Django project


#Base db container on tutum postgres container
FROM tutum/postgresql

#Load in clean purple robot warehouse database

MAINTAINER "Amos A Folarin <amosfolarin@gmail.com>"

